import glm

height = 1080
width = 1920
WIN_SIZE = (width, height)

BG_COLOR = (1.0, 0.5, 0.5)

# 摄像机画面宽高比
ASPECT_RATIO = WIN_SIZE[0] / WIN_SIZE[1]
V_FOV = glm.radians(50)
H_FOV = glm.atan(glm.tan(V_FOV / 2) * ASPECT_RATIO)
NEAR = 0.1
FAR = 2000
PITCH_MAX = glm.radians(89)

PLAYER_WALK_SPEED = 0.005
# PLAYER_ROTATE_SPEED = 0.003
PLAYER_SENSITIVITY = 0.002
PLAYER_POS = glm.vec3(0.0, 0.0, 3.0)


CHUNK_SIZE = 32
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
