import glm

height = 1080
width = 1920
WIN_SIZE = (width, height)

BG_COLOR = glm.vec3(0.58, 0.83, 0.99)
FOG_DENSITY = 0.00001

# 摄像机画面宽高比
ASPECT_RATIO = WIN_SIZE[0] / WIN_SIZE[1]
V_FOV = glm.radians(50)
H_FOV = 2 * glm.atan(glm.tan(V_FOV / 2) * ASPECT_RATIO)
NEAR = 0.1
FAR = 2000
PITCH_MAX = glm.radians(89)


CHUNK_SIZE = 48
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
CHUNK_SPHERE_RADIUS = H_CHUNK_SIZE * glm.sqrt(3)

WORLD_W, WORLD_H, WORLD_D = 10, 2, 10
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H
CENTER_XZ = WORLD_W * H_CHUNK_SIZE
CENTER_Y = WORLD_H * H_CHUNK_SIZE


PLAYER_WALK_SPEED = 0.02
# PLAYER_ROTATE_SPEED = 0.003
PLAYER_SENSITIVITY = 0.004
PLAYER_POS = glm.vec3(CENTER_XZ, CENTER_Y, CENTER_XZ)

MAX_RAY_DIST = 12

SAND = 1
GRASS = 2
DIRT = 3
STONE = 4
SNOW = 5
LEAVES = 6
WOOD = 7

SNOW_LVL = 54
STONE_LVL = 49
DIRT_LVL = 40
GRASS_LVL = 8
SAND_LVL = 7

TREE_PROBABILITY = 0.02
TREE_WIDTH, TREE_HEIGHT = 4, 8
H_TREE_WIDTH, H_TREE_HEIGHT = TREE_WIDTH // 2, TREE_HEIGHT // 2

WATER_LINE = 5.8
WATER_AMPLIFY_SCALE = 5 * CHUNK_SIZE * WORLD_W
